server.port: 8098

spring:
  application.name: quickstart

  output.ansi.enabled: always

  h2.console.enabled: true
  datasource.hikari:
    driver-class-name: org.h2.Driver
    jdbc-url: jdbc:h2:~/test1
    username: sa
    password:

mybatis.mapper-locations: mappers/*.xml
